stages:
  - lint
  - build
.lint:
  image: stepanstipl/ansible
  stage: lint
  script:
    - ansible-lint -x "ANSIBLE0006" build-centos?-ansible.yml
.ansible-centos6:
  variables:
    TAG: stable-2.3
  image: centos:6
  stage: build
  script:
    - yum install epel-release -y
    - yum install ansible git -y
    #- export TAG=$(git ls-remote --tags https://github.com/ansible/ansible.git refs/tags/*-1|tail -1|awk '{print $2}'|cut -d / -f 3)
    - echo $TAG
    - ansible-playbook build-centos6-ansible.yml -v -e "result_dir=$CI_PROJECT_DIR ansible_git_version=$TAG"
  artifacts:
    paths:
    - '*.rpm'
ansible-centos7:
  variables:
    TAG: stable-2.4
  image: centos:7
  stage: build
  script:
    - yum install -y epel-release
    - >
      yum install -y which asciidoc tar ansible rpm-build
      python-setuptools python-devel git python-jinja2 libyaml-devel python-sphinx pytest
    - git clone https://github.com/ansible/ansible.git -b $TAG --recursive
    - cd ansible
    - make rpm
  artifacts:
    paths:
    - "$CI_PROJECT_DIR/ansible/rpm-build/*.rpm"
