stages:
  - lint
  - build
lint:
  image: stepanstipl/ansible
  stage: lint
  script:
    - ansible-lint -x "ANSIBLE0006" build-centos?-ansible.yml
ansible-centos6:
  image: scottmiller171/ansible-docker-images:centos-6
  stage: build
  script:
    - ansible-playbook build-centos6-ansible.yml -e "result_dir=$CI_PROJECT_DIR"
  artifacts:
    paths:
    - '*.rpm'
ansible-centos7:
  image: scottmiller171/ansible-docker-images:centos-7
  stage: build
  script:
    - ansible-playbook build-centos7-ansible.yml -e "result_dir=$CI_PROJECT_DIR"
  artifacts:
    paths:
    - '*.rpm'
