variables:
  ANSIBLE_VERSION: v2.4.2.0-1

stages:
  - lint
  - build
lint:
  image: stepanstipl/ansible
  stage: lint
  script:
    - ansible-lint -x "ANSIBLE0006" build-centos?-ansible.yml
ansible-centos6:
  image: centos:6
  stage: build
  script:
    - sh build-centos6-ansible
    - mv ./ansible/rpm-build/*.noarch.rpm .
  artifacts:
    paths:
    - '*.rpm'
ansible-centos7:
  image: centos:7
  stage: build
  script:
    - sh build-centos7-ansible
    - mv ./ansible/rpm-build/*.noarch.rpm .
  artifacts:
    paths:
    - '*.rpm'
