stages:
#  - lint
  - build
.lint-centos6:
  stage: lint
  script:
    - ansible-lint -x "ANSIBLE0006" rebuild-centos6-ansible.yml
.lint-centos7:
  stage: lint
  script:
    - ansible-lint -x "ANSIBLE0006" build-centos7-ansible.yml
build-centos6:
  image: centos:6
  stage: build
  script:
    - yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm -y
    - yum install python-pip -y
    - yum install which asciidoc tar "@Development tools" python-setuptools python2-devel libyaml-devel asciidoc git python-jinja2 python-sphinx python-markupsafe pytest -y
    - curl -s https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh | sh
    - ansible-playbook build-centos6-ansible.yml -e "result_dir=$CI_PROJECT_DIR"
    - ls *.rpm | xargs -I {} sh -c "md5 -q {} > {}.md5"
  artifacts:
    paths:
    - '*.rpm'
    - '*.rpm.md5'
.build-centos7:
  stage: build
  script:
    - ansible-playbook build-centos7-ansible.yml -e "result_dir=$CI_PROJECT_DIR"
    - ls *.rpm | xargs -I {} sh -c "md5 -q {} > {}.md5"
  artifacts:
    paths:
    - '*.rpm'
    - '*.rpm.md5'
