variables:
  ANSIBLE_VERSION: v2.4.1.0-1

stages:
  - lint
  - build
lint:
  image: stepanstipl/ansible
  stage: lint
  script:
    - ansible-lint -x "ANSIBLE0006" build-centos?-ansible.yml
ansible-centos6:
  image: centos:6
  stage: build
  script:
    - sh build-sentos6-ansible
  artifacts:
    paths:
    - 'ansible/rpm-build/*.rpm'
ansible-centos7:
  image: centos:7
  stage: build
  script:
    - sh build-sentos7-ansible
  artifacts:
    paths:
    - 'ansible/rpm-build/*.rpm'
