---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
      - name: enable all repos
        replace:
          dest: /etc/yum.repos.d/CentOS-Base.repo
          regexp: ^enabled=0
          replace: enabled=1
      - name: Install rpms
        yum: name={{ item }} state=present
        with_items:
            - which
            - asciidoc
            - tar
            - "@Development tools"
            - python-setuptools
            - python-devel
            - git
            - python-jinja2
            - libyaml-devel
            - python-sphinx
            - pytest

      - name: create build dir
        file: path={{build_dir}} state=directory

      - name: Clone ansible git
        git:
          repo: https://github.com/ansible/ansible.git
          dest: "{{build_dir}}"
          recursive: yes
          version: "{{ansible_git_version}}"

      - name: Build rpm
        command: make rpm chdir={{build_dir}} creates={{build_dir}}/rpm-build

      - name: find rpms
        find: paths="{{build_dir}}/rpm-build" patterns="*.rpm"
        register: rpms

      - name: copy rpms to {{result_dir}}
        copy: src={{item.path}} dest={{result_dir}} remote_src=yes
        with_items: "{{rpms.files}}"

      - name: install jinja2 src rpm
        command: rpm -i https://dl.dropboxusercontent.com/u/2296931/python-jinja2/python-jinja2-2.8-5.fc24.src.rpm?dl=1 creates=/root/rpmbuild/SPECS/python-jinja2.spec

      - name: download spec file
        get_url:
          url: https://dl.dropboxusercontent.com/u/2296931/python-jinja2/python-jinja2.spec?dl=1
          dest: /root/rpmbuild/SPECS/python-jinja2.spec

      - name: build python-jinja2
        command: rpmbuild -bb /root/rpmbuild/SPECS/python-jinja2.spec creates=/root/rpmbuild/RPMS/noarch

      - name: find jinja2 rpms
        find: paths="/root/rpmbuild/RPMS/noarch" patterns="*.rpm"
        register: j2rpms

      - name: copy rpms to /vol1
        copy: src={{item.path}} dest={{result_dir}} remote_src=yes
        with_items: "{{j2rpms.files}}"

  vars:
        build_dir: /tmp/rpms-build
        ansible_git_version: stable-2.2
