#!/bin/bash

yum install -y epel-release
yum install -y yum install -y which asciidoc tar "@Development tools" \
python-setuptools python2-devel libyaml-devel python-jinja2 python-sphinx \
python-markupsafe pytest python-pip
pip install --upgrade Jinja2 packaging
yum install PyYAML -y

git clone https://github.com/ansible/ansible.git --recursive
cd ansible
git checkout tags/${ANSIBLE_VERSION} || git checkout ${ANSIBLE_VERSION} || exit 1
sed -i 's/__python2/__python/g' ./packaging/rpm/ansible.spec
sed -i '/%clean/i \
cp $CI_PROJECT_DIR/ansible/lib/ansible/config/base.yml %{buildroot}%{python_sitelib}/ansible/config/base.yml' packaging/rpm/ansible.spec
make rpm
find . -name *.rpm