---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
      - name: Install rpms
        yum: name={{ item }} state=present
        with_items:
            - which
            - asciidoc
            - tar
            - "@Development tools"
            - python-setuptools
            - python2-devel
            - libyaml-devel
            - git
            - python-jinja2
            - python-sphinx
            - python-markupsafe
            - pytest

      - name: create build dir
        file: path={{build_dir}} state=directory

      - name: Clone ansible git
        git:
          repo: https://github.com/ansible/ansible.git
          dest: "{{build_dir}}"
          recursive: yes
          version: "{{ansible_git_version}}"

      - name: Build rpm
        command: make rpm chdir={{build_dir}} creates={{build_dir}}/rpm-build

      - name: find rpms
        find: paths="{{build_dir}}/rpm-build" patterns="*.rpm"
        register: rpms

      - name: copy ansible rpms to {{result_dir}}
        copy: src={{item.path}} dest={{result_dir}} remote_src=yes
        with_items: "{{rpms.files}}"

      - block:
        - name: install epel
          yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

        - name: install ansible
          yum: name={{item.path}}
          with_items: "{{rpms.files}}"

        - name: install jinja2 src rpm
          command: rpm -i https://dl.dropboxusercontent.com/u/2296931/python-jinja2/python-jinja2-2.8-5.fc24.src.rpm?dl=1 creates=/root/rpmbuild/SPECS/python-jinja2.spec

        - name: copy python-jinja2.8-rh.spec for rhel
          copy: src=python-jinja2.8-rh.spec dest=/root/rpmbuild/SPECS/python-jinja2.8-rh.spec

        - name: build python-jinja2
          command: rpmbuild -bb /root/rpmbuild/SPECS/python-jinja2.8-rh.spec creates=/root/rpmbuild/RPMS/noarch/python-jinja2-2.8-5.el6.noarch.rpm

        - name: copy python-jinja2 rpm to {{result_dir}}
          copy: src=/root/rpmbuild/RPMS/noarch/python-jinja2-2.8-5.el6.noarch.rpm dest={{result_dir}} remote_src=yes

        - name: install ansible-lint src rpm
          command: rpm -i https://dl.fedoraproject.org/pub/fedora/linux/updates/23/SRPMS/a/ansible-lint-3.2.5-1.fc23.src.rpm creates=/root/rpmbuild/SPECS/ansible-lint.spec

        - name: copy ansible-lint.spec for rhel
          copy: src=ansible-lint-rh.spec dest=/root/rpmbuild/SPECS/ansible-lint-rh.spec

        - name: build ansible-lint
          command: rpmbuild -bb /root/rpmbuild/SPECS/ansible-lint-rh.spec creates=/root/rpmbuild/RPMS/noarch/ansible-lint-3.2.5-1.el6.noarch.rpm

        - name: copy rpms to {{result_dir}}
          copy: src=/root/rpmbuild/RPMS/noarch/ansible-lint-3.2.5-1.el6.noarch.rpm dest={{result_dir}} remote_src=yes
        when: ansible_git_version != 'stable-2.2'

  vars:
        build_dir: /tmp/rpms-build
        ansible_git_version: stable-2.2
