#!/bin/bash

yum install -y epel-release

yum install -y which asciidoc tar ansible rpm-build \
python-setuptools python-devel git python-jinja2 libyaml-devel python-sphinx pytest
git clone https://github.com/ansible/ansible.git -b stable-2.4 --recursive

cd ansible
make rpm

ls rpm-build/*.rpm
