---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: create container
      docker_container:
        name: php-fpm
        image: centos:7
        state: started
        tty: yes

    - name: start second container
      docker_container:
        name: myapp
        image: centos:7
        state: started
        tty: yes
        links:
         - "php-fpm:php-server"
  vars:
      users: "{
        '{{ansible_hostname}}-alice': ['par1', 'par2'],
        '{{ansible_hostname}}-bob': ['par3', 'par4']
        }"
