---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: application service
      debug: msg="{{item}} {{users[item][0]}}"
      with_items: "{{users.keys()}}"
  vars:
      users: "{
        '{{ansible_hostname}}-alice': ['par1', 'par2'],
        '{{ansible_hostname}}-bob': ['par3', 'par4']
        }"
